This notebook will be used for the capstone project of the Coursera course.

In [2]:
import pandas as pd
import numpy as np

In [3]:
print('Hello Capstone Project Course!')

Hello Capstone Project Course!

In [5]:
web=pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
web

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                           Neighborhood
 0                                                  NaN
 1                                                  NaN
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                                NaN
 176                                                NaN
 177                                                NaN
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                                NaN

 [180 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

#get table

In [13]:
df=web[0]

In [16]:
type(df)
df.shape

(180, 3)

#drop Borough "Not assigned"

In [18]:
df.drop(df[df['Borough']=="Not assigned"].index,inplace=True)

In [39]:
df.reset_index(drop=True)
df.head()

  Postal Code           Borough                                 Neighborhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [40]:
df.shape

(103, 3)

In [41]:
Geo=pd.read_csv("http://cocl.us/Geospatial_data")

In [42]:
Geo.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [50]:
df_new=pd.merge(df,Geo, on='Postal Code')

In [51]:
df_new.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494

In [52]:
df_new.shape

(103, 5)

In [53]:
toronto_data=df_new[df_new['Borough'].str.contains("Toronto")]
toronto_data.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
15,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
19,M4E,East Toronto,The Beaches,43.676357,-79.293031

In [54]:
CLIENT_ID = '0QPRFOXDWHYK3KI04RKV1INZP5WIZZVAA5EKTEP5MTXBFAWO' # your Foursquare ID
CLIENT_SECRET = 'M055S1XISJTAXWYIZEZ3SXPQNWKASYEBPSWRTFIHUBB1O40Y' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 0QPRFOXDWHYK3KI04RKV1INZP5WIZZVAA5EKTEP5MTXBFAWO
CLIENT_SECRET:M055S1XISJTAXWYIZEZ3SXPQNWKASYEBPSWRTFIHUBB1O40Y

In [55]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [58]:
import requests # library to handle requests

In [59]:
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 500 # define radius
toronto_venues = getNearbyVenues(names=toronto_data['Neighborhood'],
                                   latitudes=toronto_data['Latitude'],
                                   longitudes=toronto_data['Longitude']
                                  )

Regent Park, Harbourfront
Queen's Park, Ontario Provincial Government
Garden District, Ryerson
St. James Town
The Beaches
Berczy Park
Central Bay Street
Christie
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
Studio District
Lawrence Park
Roselawn
Davisville North
Forest Hill North & West
High Park, The Junction South
North Toronto West
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
Rosedale
Stn A PO Boxes
St. James Town, Cabbagetown
First Canadian Place, Underground city
Church and Wellesley
Business reply mail Processing Centre

In [60]:
toronto_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
Berczy Park,55,55,55,55,55,55
"Brockton, Parkdale Village, Exhibition Place",22,22,22,22,22,22
Business reply mail Processing Centre,19,19,19,19,19,19
"CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport",16,16,16,16,16,16
Central Bay Street,66,66,66,66,66,66
Christie,17,17,17,17,17,17
Church and Wellesley,76,76,76,76,76,76
"Commerce Court, Victoria Hotel",100,100,100,100,100,100
Davisville,34,34,34,34,34,34
Davisville North,9,9,9,9,9,9
"Dufferin, Dovercourt Village",16,16,16,16,16,16
"First Canadian Place, Underground city",100,100,100,100,100,100
Forest Hill North & West,5,5,5,5,5,5
"Garden District, Ryerson",100,100,100,100,100,100
"Harbourfront East, Union Station, Toronto Islands",100,100,100,100,100,100
"High Park, The Junction South",23,23,23,23,23,23
"India Bazaar, The Beaches West",23,23,23,23,23,23
"Kensington Market, Chinatown, Grange Park",57,57,57,57,57,57
Lawrence Park,3,3,3,3,3,3
"Little Portugal, Trinity",43,43,43,43,43,43
"Moore Park, Summerhill East",2,2,2,2,2,2
North Toronto West,22,22,22,22,22,22
"Parkdale, Roncesvalles",14,14,14,14,14,14
"Queen's Park, Ontario Provincial Government",34,34,34,34,34,34
"Regent Park, Harbourfront",47,47,47,47,47,47
"Richmond, Adelaide, King",93,93,93,93,93,93
Rosedale,4,4,4,4,4,4
Roselawn,3,3,3,3,3,3
"Runnymede, Swansea",37,37,37,37,37,37
St. James Town,76,76,76,76,76,76
"St. James Town, Cabbagetown",51,51,51,51,51,51
Stn A PO Boxes,93,93,93,93,93,93
Studio District,40,40,40,40,40,40
"Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park",16,16,16,16,16,16
"The Annex, North Midtown, Yorkville",26,26,26,26,26,26
The Beaches,4,4,4,4,4,4
"The Danforth West, Riverdale",42,42,42,42,42,42
"Toronto Dominion Centre, Design Exchange",100,100,100,100,100,100
"University of Toronto, Harbord",35,35,35,35,35,35

In [61]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head()

,Yoga Studio,Accessories Store,Afghan Restaurant,Airport,Airport Food Court,Airport Gate,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,...,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Video Store,Vietnamese Restaurant,Wine Bar,Wings Joint,Women's Store
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()

In [63]:
from sklearn.cluster import KMeans

In [64]:
# set number of clusters
kclusters = 5

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters